name: CI
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      - uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: v1.64
          skip-cache: true
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: Send coverage report
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          file: coverage.txt
